# Generated by Django 5.0.7 on 2024-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='statement',
            field=models.TextField(default='No statement provided'),
        ),
    ]
