# Generated by Django 5.0.7 on 2024-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_codesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
