# Generated by Django 5.0.7 on 2024-07-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_codesubmission_verdict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input',
            new_name='input_data',
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='judge.question'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
